name: UPRT
model_type: PhaseRetrievalModel
num_gpu: 1
manual_seed: 10

datasets:
  train:
    name: Mixture-phase-train
    type: PairedFringeDataset
    dataroot_gt: datasets/train
    dataroot_lq: datasets/train
    io_backend:
      type: disk

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: FP1523-phase-validation
    type: PairedFringeDatasetTest
    dataroot_gt: datasets/validation/FP1523
    dataroot_lq: datasets/validation/FP1523
    io_backend:
      type: disk

# network structures
network_g:
  type: UPRT
  dim: 48
  num_blocks: [1,2,2]
  num_refinement_blocks: 2
  heads: [1,2,4]
  ffn_expansion_factor: 2
  splits: [4,2,1]

# path
path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-3
    weight_decay: !!float 0
    betas: [0.9, 0.99]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 200000
    eta_min: !!float 1e-7

  total_iter: 200000
  warmup_iter: -1 # no warm up
  mixup: false

  # losses
  pixel_opt:
    type: MSELoss
    loss_weight: 1.
    reduction: mean
  freq_opt:
    type: FFTLoss
    loss_weight: 0.02
    reduction: mean

# validation settings  2e4
val:
  val_freq: !!float 8000
  save_img: false
  trans_num: 1

  max_minibatch: 1

  metrics:
    RMSE: # metric name, can be arbitrary
      type: calculate_phase_rmse
      frequency: 80

# logging settings  200 1e4 
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 2000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
